//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickingDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Esdata_SMPPLEntities : DbContext
    {
        public Esdata_SMPPLEntities()
            : base("name=Esdata_SMPPLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int App_Picking_CheckingAssign(string invdt, string custCode, string block, string invnum, Nullable<int> checkerId, string checkerName)
        {
            var invdtParameter = invdt != null ?
                new ObjectParameter("Invdt", invdt) :
                new ObjectParameter("Invdt", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            var checkerIdParameter = checkerId.HasValue ?
                new ObjectParameter("CheckerId", checkerId) :
                new ObjectParameter("CheckerId", typeof(int));
    
            var checkerNameParameter = checkerName != null ?
                new ObjectParameter("CheckerName", checkerName) :
                new ObjectParameter("CheckerName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_CheckingAssign", invdtParameter, custCodeParameter, blockParameter, invnumParameter, checkerIdParameter, checkerNameParameter);
        }
    
        public virtual ObjectResult<App_Picking_New_CheckerInfo_Result> App_Picking_New_CheckerInfo(string invdt)
        {
            var invdtParameter = invdt != null ?
                new ObjectParameter("invdt", invdt) :
                new ObjectParameter("invdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Picking_New_CheckerInfo_Result>("App_Picking_New_CheckerInfo", invdtParameter);
        }
    
        public virtual ObjectResult<App_Picking_New_GetPhoneInfo_Result> App_Picking_New_GetPhoneInfo(string phoneid)
        {
            var phoneidParameter = phoneid != null ?
                new ObjectParameter("Phoneid", phoneid) :
                new ObjectParameter("Phoneid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Picking_New_GetPhoneInfo_Result>("App_Picking_New_GetPhoneInfo", phoneidParameter);
        }
    
        public virtual ObjectResult<App_Picking_New_GetPickingDetailList_Result> App_Picking_New_GetPickingDetailList(string phoneCode)
        {
            var phoneCodeParameter = phoneCode != null ?
                new ObjectParameter("PhoneCode", phoneCode) :
                new ObjectParameter("PhoneCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Picking_New_GetPickingDetailList_Result>("App_Picking_New_GetPickingDetailList", phoneCodeParameter);
        }
    
        public virtual ObjectResult<App_Picking_New_GetPickList_Result> App_Picking_New_GetPickList(string pickDate, string custCode, string phoneCode, string block, string invnum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var phoneCodeParameter = phoneCode != null ?
                new ObjectParameter("PhoneCode", phoneCode) :
                new ObjectParameter("PhoneCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Picking_New_GetPickList_Result>("App_Picking_New_GetPickList", pickDateParameter, custCodeParameter, phoneCodeParameter, blockParameter, invnumParameter);
        }
    
        public virtual ObjectResult<App_Picking_New_GetUnPickingList_Result> App_Picking_New_GetUnPickingList(string phoneid)
        {
            var phoneidParameter = phoneid != null ?
                new ObjectParameter("Phoneid", phoneid) :
                new ObjectParameter("Phoneid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_Picking_New_GetUnPickingList_Result>("App_Picking_New_GetUnPickingList", phoneidParameter);
        }
    
        public virtual int App_Picking_New_UpdateBasketNo(string pickDate, string custCode, string block, string basketNo, string invnum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(string));
    
            var basketNoParameter = basketNo != null ?
                new ObjectParameter("basketNo", basketNo) :
                new ObjectParameter("basketNo", typeof(string));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdateBasketNo", pickDateParameter, custCodeParameter, blockParameter, basketNoParameter, invnumParameter);
        }
    
        public virtual int App_Picking_New_UpdatePhoneInfo(string phoneid, string loginStatus)
        {
            var phoneidParameter = phoneid != null ?
                new ObjectParameter("Phoneid", phoneid) :
                new ObjectParameter("Phoneid", typeof(string));
    
            var loginStatusParameter = loginStatus != null ?
                new ObjectParameter("LoginStatus", loginStatus) :
                new ObjectParameter("LoginStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePhoneInfo", phoneidParameter, loginStatusParameter);
        }
    
        public virtual int App_Picking_New_UpdatePickerEndTime(string pickDate, string custCode, string block, Nullable<System.TimeSpan> endTime, string invnum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(string));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.TimeSpan));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePickerEndTime", pickDateParameter, custCodeParameter, blockParameter, endTimeParameter, invnumParameter);
        }
    
        public virtual int App_Picking_New_UpdatePickerStartTime(string pickDate, string custCode, string block, Nullable<System.TimeSpan> startTime, string invnum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.TimeSpan));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePickerStartTime", pickDateParameter, custCodeParameter, blockParameter, startTimeParameter, invnumParameter);
        }
    
        public virtual int App_Picking_New_UpdatePickingDetail(string pickDate, string custCode, string block, string invnum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(string));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePickingDetail", pickDateParameter, custCodeParameter, blockParameter, invnumParameter);
        }
    
        public virtual int App_Picking_New_UpdatePickList(string invdt, string custCode, string itemId, string picked, string basketNo, Nullable<System.TimeSpan> pickedTime, string invnum)
        {
            var invdtParameter = invdt != null ?
                new ObjectParameter("Invdt", invdt) :
                new ObjectParameter("Invdt", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var itemIdParameter = itemId != null ?
                new ObjectParameter("itemId", itemId) :
                new ObjectParameter("itemId", typeof(string));
    
            var pickedParameter = picked != null ?
                new ObjectParameter("Picked", picked) :
                new ObjectParameter("Picked", typeof(string));
    
            var basketNoParameter = basketNo != null ?
                new ObjectParameter("BasketNo", basketNo) :
                new ObjectParameter("BasketNo", typeof(string));
    
            var pickedTimeParameter = pickedTime.HasValue ?
                new ObjectParameter("PickedTime", pickedTime) :
                new ObjectParameter("PickedTime", typeof(System.TimeSpan));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePickList", invdtParameter, custCodeParameter, itemIdParameter, pickedParameter, basketNoParameter, pickedTimeParameter, invnumParameter);
        }
    
        public virtual int App_Picking_New_UpdatePickRackStatus(string pickDate, string custCode, string block, string racks, Nullable<int> slipNum)
        {
            var pickDateParameter = pickDate != null ?
                new ObjectParameter("pickDate", pickDate) :
                new ObjectParameter("pickDate", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("block", block) :
                new ObjectParameter("block", typeof(string));
    
            var racksParameter = racks != null ?
                new ObjectParameter("Racks", racks) :
                new ObjectParameter("Racks", typeof(string));
    
            var slipNumParameter = slipNum.HasValue ?
                new ObjectParameter("SlipNum", slipNum) :
                new ObjectParameter("SlipNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdatePickRackStatus", pickDateParameter, custCodeParameter, blockParameter, racksParameter, slipNumParameter);
        }
    
        public virtual int App_Picking_New_UpdateUnPickList(string invdt, string custCode, string itemId, string batchid, string invnum)
        {
            var invdtParameter = invdt != null ?
                new ObjectParameter("Invdt", invdt) :
                new ObjectParameter("Invdt", typeof(string));
    
            var custCodeParameter = custCode != null ?
                new ObjectParameter("custCode", custCode) :
                new ObjectParameter("custCode", typeof(string));
    
            var itemIdParameter = itemId != null ?
                new ObjectParameter("itemId", itemId) :
                new ObjectParameter("itemId", typeof(string));
    
            var batchidParameter = batchid != null ?
                new ObjectParameter("Batchid", batchid) :
                new ObjectParameter("Batchid", typeof(string));
    
            var invnumParameter = invnum != null ?
                new ObjectParameter("Invnum", invnum) :
                new ObjectParameter("Invnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_Picking_New_UpdateUnPickList", invdtParameter, custCodeParameter, itemIdParameter, batchidParameter, invnumParameter);
        }
    }
}
